#ifndef _LIB_CONFIG_H
#define _LIB_CONFIG_H

#include "../main/main.h"

#define CONFIG_USE_74HC595
#define CONFIG_USE_PCF8574
#define CONFIG_USE_I2CDEV
#define CONFIG_USE_LCDI2C
#define CONFIG_USE_HD44780
#define CONFIG_USE_STRING_UTILITY
#define CONFIG_USE_POSTGET
// #define CONFIG_USE_DS3231
#endif